mybatis:
#  mapperLocations: classpath:mapper/*.xml #mapper扫描路径
#  typeAliasesPackage: com.zhz.entity #bean路径
  configuration:
      mapUnderscoreToCamelCase: true  #mybatis支持驼峰
logging:
    level:
        ROOT: WARN
        org.springframework.web: WARN
    path: ../../logs
endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true