# Spring properties
spring:
  application:
     name: config-service  # Service registers under this name
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zoeminghong/spring-cloud-demo.git
          search-paths: config-repo
          username: username
          password: password
          basedir: /Users/gjason/project/springcloud/configTemp
      name: appzone #application name
      label: master #分支
#  profiles:
#    active: native #链接本地配置


# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://root:123456@${eureka.instance.hostname}:8761/eureka/

# HTTP Server
server:
  port: 7001   # HTTP (Tomcat) port





