# Spring properties
spring:
  application:
     name: config-service  # Service registers under this name
#  freemarker:
#    enabled: false           # Ignore Eureka dashboard FreeMarker templates
#  thymeleaf:
#    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zoeminghong/spring-cloud-demo.git
          search-paths: config-repo
          username: username
          password: password
  profiles:
    active: native


# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 7001   # HTTP (Tomcat) port





